SELECT * FROM ALL_CONSTRAINTS WHERE TABLE_NAME = 'pay'; SELECT A.UNIQUENESS, B.* FROM ALL_INDEXES A, ALL_IND_COLUMNS B WHERE A.INDEX_NAME = B.INDEX_NAME AND A.TABLE_NAME='pay';
SELECT * FROM USER_CONS_COLUMNS ORDER BY TABLE_NAME;

