DROP TABLE USERTABLE;

CREATE TABLE USERTABLE (
    USER_NO NUMBER PRIMARY KEY,
    EMAIL VARCHAR2(100) UNIQUE,
    USER_ID VARCHAR2(32) NOT NULL,
    USER_PW VARCHAR2(32) NOT NULL,
    USER_NAME VARCHAR2(50),
    USER_NICK VARCHAR2(50),
    USER_TEL VARCHAR2(13),
    USER_GRADE VARCHAR2(6),
    USER_DATE DATE,
    BIRTHDAY VARCHAR2(10),
    STATE NUMBER(1),
    POINT NUMBER(4),
    AD_NO VARCHAR2(32),
    AD_ID VARCHAR2(32)
);